apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alpha
  namespace: argocd
spec:
  description: "ArgoCD Project created using yaml"
  sourceRepos:
    - 'https://github.com/Juhith-Narendra/ArgoCD.git'
    - 'https://github.com/mabusaa/argocd-course-app-of-apps.git'
    - 'https://github.com/mabusaa/argocd-example-apps.git'
    - 'https://github.com/kubecost/cost-analyzer-helm-chart.git'
  destinations:
    - namespace: argocd-juhith
      server: 'https://kubernetes.default.svc'
    - namespace: argocd
      server: 'https://kubernetes.default.svc'  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: "Admin role with all permissions"
      policies:
        - p, role:admin, applications, *, project-alpha/*, allow
      groups:
        - ArgoCD-Project-alpha-admins
    - name: reader
      description: "Reader role with view permissions"
      policies:
        - p, role:reader, applications, get, project-alpha/*, allow
      groups:
        - ArgoCD-Project-alpha-readers